creates lint workflow for future prs

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -13,6 +13,25 @@ jobs:
     runs-on: ubuntu-latest
     steps: 
       - uses: actions/checkout@v4
+      
       - uses: actions/setup-node@v4
         with:
-          node-version-file: ".nvmrc"
+          node-version-file: '.nvmrc'
+          cache: yarn
+
+      - name: Install Dependencies
+        run: yarn install --frozen-lockfile
+
+      -name: Run Linter
+        run: yarn lint
+        continue-on-error: false
+
+      - name: Check if autofixes available
+        run: |
+          git add --all
+          changes=$(git diff --cached -name-only)
+
+          if [ -n "$changes" ]; then
+            echo "Error: There are autofixes available. Run 'yarn lint --fix'. Make sure your dependencies are updated!"
+            exit 1
+          fi
